apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ./argocd-declarative/manifests/argocd-app
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    directory:
      exclude: '*-local-*'
      recurse: true
  sources: []
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true