apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    path: ./argocd-declarative/manifests/cert-manager-app

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
