apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: git-ops
    server: https://kubernetes.default.svc
  source:
    path: ./argocd-declarative/manifests/gitea-app
#    repoURL: https://gitea.int.taqniat.ae/twasol/git-ops.git
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    directory:
      exclude: '*-local-*'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true