apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-volume-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    path: ./argocd-declarative/manifests/nfs-volume-app

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-client

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true