apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    path: ./argocd-declarative/manifests/tekton-app
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true