apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kube-craft/git-ops.git
    targetRevision: HEAD
    path: ./argocd-declarative/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true