apiVersion: v1
kind: Service
metadata:
  name: tempo-svc
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      name: tempo
      port: 3200
      targetPort: 3200
    - protocol: TCP
      name: zipkin
      port: 9411
      targetPort: 9411
#      nodePort: 32007
#  type: NodePort
  type: ClusterIP