apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
#  namespace: default
data:
  config.yml: |      # Paste the content of your tempo.yaml file below
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000