apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-nfs-sc
  annotations:
    nfs.io/storage-path: /grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-client-sc"