apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-pod-reader-global-role
#  namespace: <your-prometheus-namespace>
rules:
#- apiGroups: [""]
#  # at the HTTP level, the name of the resource for accessing Secret
#  # objects is "secrets"
#  verbs: ["get", "watch", "list"]
#  resources: ["pods", "pods/log"]
#- apiGroups: [""] # "" indicates the core API group
#  verbs: ["get", "list", "watch"]
#  resources: ["nodes", "nodes/proxy"]
- apiGroups: [""] # "" indicates the core API group
  verbs: ["*"]
  resources: ["*"]