apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "dev" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: prometheus-pod-reader-global-role-binding
#  namespace: <your-prometheus-namespace>
subjects:
#- kind: User
#  name: pavan # "name" is case sensitive
#  apiGroup: rbac.authorization.k8s.io
#- kind: Group
#  name: dev # "name" is case sensitive
#  apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: prometheus-sa
#    namespace: default
    namespace: git-ops
roleRef:
  kind: ClusterRole
  name: prometheus-pod-reader-global-role
  apiGroup: rbac.authorization.k8s.io