apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      name: loki
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
#          image: grafana/loki:2.9.2
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/loki/local-config.yml
#            - --config.file=/etc/loki/config.yml
#            - --target=backend
#            - --legacy-read-mode=false
          ports:
            - containerPort: 3100
              protocol: TCP
#          resources:
#            limits:
#              memory: "700Mi"
          volumeMounts:
            - name: loki-vol
              mountPath: /tmp/loki
            - name: loki-config
#              mountPath: /etc/loki                      # it will remove the directory and just map this file,
              mountPath: /etc/loki/local-config.yml     # this will only mount this file and rest will keep intact
              subPath: local-config.yml
      restartPolicy: Always
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: "local-config.yml"
                path: "local-config.yml"
        - name: loki-vol
          persistentVolumeClaim:
#            claimName: loki-pvc-local
            claimName: loki-pvc-nfs-sc