apiVersion: v1
kind: Service
metadata:
  name: loki-svc
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
#      nodePort: 32006
#  type: NodePort
  type: ClusterIP