apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-hostpath-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /k8s_hostpath/data/postgres  # Path on the Docker Desktop host machine
    type: DirectoryOrCreate