apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-nfs-sc
  annotations:
    nfs.io/storage-path: /prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "nfs-client-sc"