apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.100-192.168.1.110  # Change this to your subnet range
  # - 192.168.10.0/24
  # - 192.168.9.1-192.168.9.5
  # - fc00:f853:0ccd:e799::/124    
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
