apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-sc
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME
parameters:
#  pathPattern: "${.PVC.namespace}-${.PVC.name}"  # folder will be named like <pvc-namespace>-<pvc-name>
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}" # waits for nfs.io/storage-path annotation, if not specified will accept as empty string.
#  onDelete: delete
  onDelete: retain
#  archiveOnDelete: "true"